import { Inter } from "next/font/google";
import "./globals.css";
import NavbarUp from "./components/NavbarUp";
import MiddleNav from "./components/MiddleNav";
import Hero from "./components/HeroNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavbarUp/>
    <MiddleNav/>
    <Hero />

        {children}</body>
    </html>
  );
}
